### ISSUE TITLE
19-07-2017: WebStorm version

### ISSUE THREAD

**Issue by Drapegnik** [jakwuh/dailytip#1]
Can you specify your `WebStorm` version, cause in `2017.1`, it looks like:

<img width="567" alt="screen shot 2017-07-26 at 12 47 20" src="https://user-images.githubusercontent.com/11758660/28615187-e523efd8-7200-11e7-844d-8a6d0f180a5c.png">

![screen shot 2017-07-26 at 12 50 44](https://user-images.githubusercontent.com/11758660/28615228-10be47d8-7201-11e7-9b9f-464dd433208b.png)

**Comment by jakwuh** [comment]
I have WS2017.2. Could you try updating your version to see if the option appears?

**Comment by jakwuh** [comment]
@Drapegnik any update on this?

**Comment by Drapegnik** [comment]
@jakwuh yes, I update and everything is ok
